//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB)
// Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source
// schema.
// Generated on: 2014.12.15 at 10:49:28 PM CET
//

@XmlSchema(namespace = "http://collonville.thomas.fr/tc-osgi-bundle-utils/config-file-schema", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.tc.osgi.bundle.utils.conf.jaxb;

import jakarta.xml.bind.annotation.XmlSchema;
